### ISSUE TITLE
R9.4.1 data with a 6024 sampling rate?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#342]
I am using dorado-0.3.2. I tried to basecall this old R9.4.1 dataset. 
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/combined_2018-08-10.raw_fast5s.5.tar

I first convert into multi and then pod5 but then it crashed with this error
  [2023-08-18 09:41:17.678] [error] Sample rate for model (4000) and data (6024) are not compatible.

This data supposedly run on a mix of RAD003 and RAD004. When I run pod5 inspect, I noticed that some are rad004 at 4000 sampling rate but some are rad003 at 6024 sampling rate. Does RAD003 always run at 6024? If so, does that mean dorado doesn't support RAD003?

```
Run info 0:
        acquisition_id: 75b6a19d2c151c49e1214f7cf59b7fef48490023
        acquisition_start_time: 2018-05-04 17:31:06+00:00
        adc_max: 4095
        adc_min: -4096
        context_tags: {'experiment_duration_set': '2880', 'experiment_type': 'genomic_dna', 'fast5_output_fastq_in_hdf': '0', 'fast5_raw': '1', 'fast5_reads_per_folder': '4000', 'fastq_enabled': '0', 'fastq_reads_per_file': '4000', 'filename': 'dn52eoh3_sunet_20180504_fah36586_mn21180_sequencing_run_halfprecip_40006', 'flowcell_type': 'flo-min106', 'kit_classification': 'none', 'local_basecalling': '0', 'local_bc_comp_model': '', 'local_bc_temp_model': 'template_r9.4_450bps_5mer_raw.jsn', 'sample_frequency': '4000', 'sequencing_kit': 'sqk-rad004', 'user_filename_input': 'halfprecip'}
        experiment_name:
        flow_cell_id: FAH36586
        flow_cell_product_code:
        protocol_name: eb2b8fa71ff785fe3be43d5737406c600e3add40-096a06578eab4f4d0c2ef3b3213b1a491de8d78d
        protocol_run_id: 662014df-f2a9-4df6-a3f2-d94d2284bcd7
        protocol_start_time: 1970-01-01 00:00:00+00:00
        sample_id: HalfPrecip
        sample_rate: 4000
        sequencing_kit: sqk-rad004
        sequencer_position: MN21180
        sequencer_position_type: minion
        software: python-pod5-converter
        system_name:
        system_type:
        tracking_id: {'asic_id': '556147114', 'asic_id_eeprom': '2032938', 'asic_temp': '44.761219', 'auto_update': '0', 'auto_update_source': 'https://mirror.oxfordnanoportal.com/software/MinKNOW/', 'bream_is_standard': '0', 'device_id': 'MN21180', 'device_type': 'minion', 'exp_script_name': 'eb2b8fa71ff785fe3be43d5737406c600e3add40-096a06578eab4f4d0c2ef3b3213b1a491de8d78d', 'exp_script_purpose': 'sequencing_run', 'exp_start_time': '2018-05-04T17:31:06Z', 'flow_cell_id': 'FAH36586', 'heatsink_temp': '33.996094', 'hostname': 'DN52eoh3.SUNet', 'installation_type': 'nc', 'local_firmware_file': '1', 'operating_system': 'Darwin 16.7.0', 'protocol_run_id': '662014df-f2a9-4df6-a3f2-d94d2284bcd7', 'protocols_version': '0.0.0.0', 'run_id': '75b6a19d2c151c49e1214f7cf59b7fef48490023', 'sample_id': 'HalfPrecip', 'usb_config': 'firm_1.2.3_ware#rbt_4.5.6_rbt#ctrl#USB3', 'version': '1.11.5'}
Run info 1:
        acquisition_id: ca3eb9dd3816309ab560972ca8cc78700d9ac19c
        acquisition_start_time: 2017-09-12 23:18:04+00:00
        adc_max: 4095
        adc_min: -4096
        context_tags: {'experiment_duration_set': '2880', 'experiment_type': 'genomic_dna', 'fast5_output_fastq_in_hdf': '0', 'fast5_raw': '1', 'fast5_reads_per_folder': '4000', 'fastq_enabled': '0', 'fastq_reads_per_file': '4000', 'filename': 'dn52eo08_sunet_20170912_fah03763_mn21180_sequencing_run_hg002_ultralong_quick_b_66264', 'flowcell_type': 'flo-min107', 'local_basecalling': '0', 'local_bc_comp_model': '', 'local_bc_temp_model': 'template_r9.5_450bps_5mer.jsn', 'sample_frequency': '6024', 'sequencing_kit': 'sqk-rad003', 'user_filename_input': 'hg002_ultralong_quick_b'}
        experiment_name:
        flow_cell_id: FAH03763
        flow_cell_product_code:
        protocol_name: 80
        protocol_run_id: 0fafecc2-5aa6-4c35-976e-9439b314e8be
        protocol_start_time: 1970-01-01 00:00:00+00:00
        sample_id: HG002_ultralong_quick_b
        sample_rate: 6024
        sequencing_kit: sqk-rad003
        sequencer_position: MN21180
        sequencer_position_type: minion
        software: python-pod5-converter
        system_name:
        system_type:
        tracking_id: {'asic_id': '2769950373', 'asic_id_eeprom': '1990756', 'asic_temp': '35.269997', 'auto_update': '1', 'auto_update_source': 'https://mirror.oxfordnanoportal.com/software/MinKNOW/', 'bream_core_version': '1.7.14.1', 'bream_is_standard': '0', 'bream_ont_version': '1.7.14.1', 'device_id': 'MN21180', 'exp_script_name': '80', 'exp_script_purpose': 'sequencing_run', 'exp_start_time': '2017-09-12T23:18:04Z', 'flow_cell_id': 'FAH03763', 'heatsink_temp': '34.332031', 'hostname': 'DN52eo08.SUNet', 'installation_type': 'map', 'local_firmware_file': '0', 'operating_system': 'Darwin 16.7.0', 'protocol_run_id': '0fafecc2-5aa6-4c35-976e-9439b314e8be', 'protocols_version': '1.7.14', 'run_id': 'ca3eb9dd3816309ab560972ca8cc78700d9ac19c', 'sample_id': 'HG002_ultralong_quick_b', 'usb_config': '1.1.1_ONT#MinION_fpga_1.1.0#ctrl#Auto', 'version': '1.7.14'}
```
